/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BEKUIN;

import javax.swing.JOptionPane;
import BEKUIN.Koneksi;
import BEKUIN.session;

public class MenuKasir extends javax.swing.JFrame {

    /**
     * Creates new form MenuKasir
     */
    public MenuKasir() {
        initComponents();
        NamaKasir.setText(session.get_nama_user());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NamaKasir = new javax.swing.JLabel();
        KelolaBarang = new javax.swing.JButton();
        KasirKelolaPelanggan = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        LaporanHarian = new javax.swing.JButton();
        LaporanPembeliPelanggan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setText("Selamat Datang");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel2.setText("Kasir :");

        NamaKasir.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        NamaKasir.setText("Nama Kasir");

        KelolaBarang.setBackground(new java.awt.Color(44, 62, 76));
        KelolaBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        KelolaBarang.setForeground(new java.awt.Color(255, 255, 255));
        KelolaBarang.setText("Transaksi");
        KelolaBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KelolaBarangMouseClicked(evt);
            }
        });
        KelolaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelolaBarangActionPerformed(evt);
            }
        });

        KasirKelolaPelanggan.setBackground(new java.awt.Color(44, 62, 76));
        KasirKelolaPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        KasirKelolaPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        KasirKelolaPelanggan.setText("Data Pelanggan");
        KasirKelolaPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KasirKelolaPelangganMouseClicked(evt);
            }
        });
        KasirKelolaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KasirKelolaPelangganActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(224, 52, 68));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("LOGOUT");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        LaporanHarian.setBackground(new java.awt.Color(44, 62, 76));
        LaporanHarian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LaporanHarian.setForeground(new java.awt.Color(255, 255, 255));
        LaporanHarian.setText("Laporan Harian");
        LaporanHarian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaporanHarianMouseClicked(evt);
            }
        });
        LaporanHarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanHarianActionPerformed(evt);
            }
        });

        LaporanPembeliPelanggan.setBackground(new java.awt.Color(44, 62, 76));
        LaporanPembeliPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LaporanPembeliPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        LaporanPembeliPelanggan.setText("Rekap Pembeli");
        LaporanPembeliPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaporanPembeliPelangganMouseClicked(evt);
            }
        });
        LaporanPembeliPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPembeliPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NamaKasir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(logout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KelolaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LaporanHarian))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KasirKelolaPelanggan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LaporanPembeliPelanggan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NamaKasir))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KelolaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KasirKelolaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LaporanPembeliPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LaporanHarian, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KelolaBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KelolaBarangMouseClicked
        new Transaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KelolaBarangMouseClicked

    private void KelolaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelolaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelolaBarangActionPerformed

    private void KasirKelolaPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KasirKelolaPelangganMouseClicked
        new KelolaPelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KasirKelolaPelangganMouseClicked

    private void KasirKelolaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KasirKelolaPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KasirKelolaPelangganActionPerformed

    private void LaporanHarianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanHarianMouseClicked
        // TODO add your handling code here:
        new RekapTransaksiHarian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LaporanHarianMouseClicked

    private void LaporanHarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanHarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaporanHarianActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
      int n = JOptionPane.showConfirmDialog(  
                null,
                "Yakin ingin logout" ,
                "",
                JOptionPane.YES_OPTION,
                JOptionPane.CLOSED_OPTION);

      if(n == JOptionPane.YES_OPTION)
      {
        new Login().setVisible(true);
        this.dispose();
      }
    }//GEN-LAST:event_logoutMouseClicked

    private void LaporanPembeliPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanPembeliPelangganMouseClicked
        // TODO add your handling code here:
        new RekapPembeli().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LaporanPembeliPelangganMouseClicked

    private void LaporanPembeliPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPembeliPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaporanPembeliPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KasirKelolaPelanggan;
    private javax.swing.JButton KelolaBarang;
    private javax.swing.JButton LaporanHarian;
    private javax.swing.JButton LaporanPembeliPelanggan;
    private javax.swing.JLabel NamaKasir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
